name: Deploy Event Signup

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'eu-north-1' }}

    - name: Install EF Core tools
      run: dotnet tool install --global dotnet-ef
  
    - name: Restore dependencies
      working-directory: ./lambda
      run: dotnet restore

    - name: Apply EF Core migrations
      working-directory: ./lambda
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      run: dotnet ef database update

    - name: Publish .NET Lambda
      working-directory: ./lambda
      run: dotnet publish -c Release -o ./publish --self-contained false

    - name: Run tests
      working-directory: ./lambda
      run: dotnet test --verbosity normal

    - name: Deploy CDK stack
      if: success()
      run: cdk deploy --require-approval never
